### ISSUE TITLE
User can turn their car

### ISSUE THREAD

**Issue by ellie-hwang** [ellie-hwang/driving-game#2]
## 💰 Motivation

The user needs to be able to control which way their car is facing.

## 📐 Plan

Rotate the image with CSS classes when the user presses an arrow key.

## ✅ Task List

- [x] Create data model for you car with a 'orientation' property that can have the values of north, south, west or east
- [x] Create CSS rules to rotate the car image 
- [x] Create an eventListener that changes the direction of the car image when a keydown event occurs
