### ISSUE TITLE
User can start their car

### ISSUE THREAD

**Issue by ellie-hwang** [ellie-hwang/driving-game#3]
## 💰 Motivation

It's a driving game, duh!

## 📐 Plan

Move the car a few pixels every 16 milliseconds when the user presses space.

## ✅ Task List

- [x] Add x y properties to the data model
- [x] Absolutely position the car image
- [x] Define a function to move your car (this will be your callback function for your setInterval function)
- [x] Use the style property of element objects to change your car's top and left box offset styles.
- [x] Add a setInterval function (the car should "move" every 16 milliseconds)
- [x] Make sure to update the x and y property values on the data model every time the car "moves"
