### ISSUE TITLE
User can stop their car

### ISSUE THREAD

**Issue by ellie-hwang** [ellie-hwang/driving-game#4]
## 💰 Motivation

If the user cannot stop their car, it goes off the page.

## 📐 Plan

Stop the car if the user presses space again.

## ✅ Task List

- [x] Add a boolean to your data model to indicate whether or not the car is started
- [x] If the keyCode matches the code for the spacebar and moving = true, stop the car. Change the value of moving to false.
- [x] If the keyCode matches the code for the spacebal and moving = false, start the car Change the value of moving to true.
