### ISSUE TITLE
User can steer their car

### ISSUE THREAD

**Issue by ellie-hwang** [ellie-hwang/driving-game#5]
## 💰 Motivation

Our game needs MAXIMUM realism to be immersive 😂.

## 📐 Plan

Change the car's location based on which direction it is facing.

## ✅ Task List

- [x] In your startCar function, set some conditions where the data.orientation value is checked. 
- [x] Increment the x and y values and assign the values to the left and top properties of the image element
- [x] Update your data.x and data.y property values on the data model
